#ifndef TUIM_COLOR_H
#define TUIM_COLOR_H

#include <stdint.h>

// TODO: add colors shit
typedef enum {
    TUIM_BLACK,
    TUIM_RED,
    TUIM_GREEN,
    TUIM_YELLOW,
    TUIM_BLUE,
    TUIM_MAGENTA,
    TUIM_CYAN,
    TUIM_WHITE,

    TUIM_BRIGHT_BLACK,
    TUIM_BRIGHT_RED,
    TUIM_BRIGHT_GREEN,
    TUIM_BRIGHT_YELLOW,
    TUIM_BRIGHT_BLUE,
    TUIM_BRIGHT_MAGENTA,
    TUIM_BRIGHT_CYAN,
    TUIM_BRIGHT_WHITE
} TuimColorIndex;

typedef enum {
    TUIM_COLOR_TYPE_NONE,
    TUIM_COLOR_TYPE_INDEXED,
    TUIM_COLOR_TYPE_RGB
} TuimColorType;

typedef struct {
    union color {
        TuimColorIndex indexed_color;
        struct {
            uint8_t red;
            uint8_t green;
            uint8_t blue;
        } rgb_color;
        int raw;
    };
    TuimColorType type;
} TuimColor;

#define TUIM_DEF_COLOR(name, indexed) \
    static const TuimColor name = { .indexed_color = indexed, .type = TUIM_COLOR_TYPE_INDEXED } 

// const indexed structs
TUIM_DEF_COLOR(TUIM_BLACK_STRUCT_INDEXED, 0);
TUIM_DEF_COLOR(TUIM_RED_STRUCT_INDEXED, 1);
TUIM_DEF_COLOR(TUIM_GREEN_STRUCT_INDEXED, 2);
TUIM_DEF_COLOR(TUIM_YELLOW_STRUCT_INDEXED, 3);
TUIM_DEF_COLOR(TUIM_BLUE_STRUCT_INDEXED, 4);
TUIM_DEF_COLOR(TUIM_MAGENTA_STRUCT_INDEXED, 5);
TUIM_DEF_COLOR(TUIM_CYAN_STRUCT_INDEXED, 6);
TUIM_DEF_COLOR(TUIM_WHITE_STRUCT_INDEXED, 7);
TUIM_DEF_COLOR(TUIM_BRIGHT_BLACK_STRUCT_INDEXED, 8);
TUIM_DEF_COLOR(TUIM_BRIGHT_RED_STRUCT_INDEXED, 9);
TUIM_DEF_COLOR(TUIM_BRIGHT_GREEN_STRUCT_INDEXED, 10);
TUIM_DEF_COLOR(TUIM_BRIGHT_YELLOW_STRUCT_INDEXED, 11);
TUIM_DEF_COLOR(TUIM_BRIGHT_BLUE_STRUCT_INDEXED, 12);
TUIM_DEF_COLOR(TUIM_BRIGHT_MAGENTA_STRUCT_INDEXED, 13);
TUIM_DEF_COLOR(TUIM_BRIGHT_CYAN_STRUCT_INDEXED, 14);
TUIM_DEF_COLOR(TUIM_BRIGHT_WHITE_STRUCT_INDEXED, 15);

#endif //TUIM_COLOR_H